### ISSUE TITLE
New hyper versions

### ISSUE THREAD

**Issue by Crilum** [Jai-JAP/hyper-arm-builds#1]
The latest version of Hyper is v3.2.3, so another build might be in order... I can build it if you give me instructions...

**Comment by Jai-JAP** [comment]
I'll add a workflow for that purpose...

**Comment by Crilum** [comment]
That would be great.. Then Pi-Apps can always have up-to-date debs.

**Comment by Jai-JAP** [comment]
> The latest version of Hyper is v3.2.3, so another build might be in order... I can build it if you give me instructions...

Instructions are on https://github.com/vercel/hyper#contribute

You have to make some additional changes before starting build.

1- Remove [snap block](https://github.com/vercel/hyper/blob/v3.2.3/electron-builder.json#L43-L48) and the comma in line 42 in electron-builder.json

2- Also remove all lines with mentions of `"x64",` in the [linux block](https://github.com/vercel/hyper/blob/v3.2.3/electron-builder.json#L19-L50).



For armv7l builds replace all "arm64" with "armv7l" in the linux block. And downgrade electron to ^17.0.0 in [package.json](https://github.com/vercel/hyper/blob/v3.2.3/package.json#L101)
electron >17.0.0 will not build on armv7l.

Cross compiling won't work. So u have to build arm64 on pios buster arm64 and armv7l on pios buster armhf.

**Comment by Jai-JAP** [comment]
Also Can you build the older hyper versions prior to v3.2.0 as i could not use my pi for the time being.

**Comment by Jai-JAP** [comment]
Also I added you collaborators. You can just release the builds per version with similar names as in the existing release

**Comment by Crilum** [comment]
>Cross compiling won't work. So u have to build arm64 on pios buster arm64 and armv7l on pios buster armhf.

I can't build on Bullseye?

**Comment by Crilum** [comment]
I've been trying all day, I can't build Hyper...
Latest problem is:
```
• electron-builder  version=22.14.13 os=5.15.32-v7l+
  • loaded configuration  file=/home/pi/src/hyper/electron-builder.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=native-process-working-directory@1.0.2, node-pty@0.10.1 platform=linux arch=armv7l
  • rebuilding native dependency  name=native-process-working-directory version=1.0.2
  • rebuilding native dependency  name=node-pty version=0.10.1
  • packaging       platform=linux arch=armv7l electron=17.4.2 appOutDir=dist/linux-armv7l-unpacked
  ⨯ Cannot find module '/home/pi/src/hyper/bin/cp-snapshot.js'
Require stack:
- /home/pi/src/hyper/node_modules/app-builder-lib/out/platformPackager.js
- /home/pi/src/hyper/node_modules/app-builder-lib/out/electron/ElectronFramework.js
- /home/pi/src/hyper/node_modules/app-builder-lib/out/packager.js
- /home/pi/src/hyper/node_modules/app-builder-lib/out/index.js
- /home/pi/src/hyper/node_modules/electron-builder/out/builder.js
- /home/pi/src/hyper/node_modules/electron-builder/out/cli/cli.js
- /home/pi/src/hyper/node_modules/electron-builder/cli.js
```

**Comment by Crilum** [comment]
I am on Bullseye.. I wonder if that's a problem...

**Comment by Crilum** [comment]
So actually, I can build Hyper (`yarn run dev`), but can't package it (`yarn run dist`).. The above error is what I get running `yarn run dist`.

**Comment by Crilum** [comment]
Here's an armhf build: https://drive.protonmail.com/urls/KMN5HMRYEM#j2pBvOzNCY6R

It's not a deb, just the binary

**Comment by Jai-JAP** [comment]
Try deleting the node_modules folder and start from beginning

**Comment by Crilum** [comment]
I've tried like three times, but ok..

**Comment by Jai-JAP** [comment]
> I've tried like three times, but ok..

Tried deleting node_nodules?

**Comment by Crilum** [comment]
Deleting the whole hyper dir and starting over..

**Comment by Jai-JAP** [comment]
Did this work for arm64

**Comment by Crilum** [comment]
I didn't try arm64.. I only usually use armhf.

**Comment by Jai-JAP** [comment]
Also try on buster maybe an issue

**Comment by Crilum** [comment]
Yeah.. Maybe I'll try that.

**Comment by Jai-JAP** [comment]
Try again after running `npm install app-builder-lib` in hyper folder

**Comment by Jai-JAP** [comment]
Also publish the build artifacts built on buster to maintain glibc compatibility

**Comment by Crilum** [comment]
Well, I've gotten farther, but it's packaging x86 stuff:
```
 electron-builder  version=22.14.13 os=5.15.32-v7l+
  • loaded configuration  file=/home/pi/src/hyper/electron-builder.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=native-process-working-directory@1.0.2, node-pty@0.10.1 platform=linux arch=armv7l
  • rebuilding native dependency  name=native-process-working-directory version=1.0.2
  • rebuilding native dependency  name=node-pty version=0.10.1
  • packaging       platform=linux arch=armv7l electron=17.4.2 appOutDir=dist/linux-armv7l-unpacked
  • building        target=AppImage arch=armv7l file=dist/Hyper-3.2.3-armv7l.AppImage
  • building        target=deb arch=armv7l file=dist/hyper_3.2.3_armv7l.deb
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86/fpm-1.9.3-2.3.1-linux-x86.7z size=4.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86/fpm-1.9.3-2.3.1-linux-x86.7z duration=3.498s

```

**Comment by Jai-JAP** [comment]
Oops I forgot an important step.. you have to install ruby and fpm
Run:
```
sudo apt install ruby libarchive-tools -y
sudo gem install fpm --no-document
export USE_SYSTEM_FPM=true
```
and continue with `yarn run dist`

**Comment by Crilum** [comment]
Here's an armhf [deb](https://drive.protonmail.com/urls/CNJRNF74E8#KNLTRvOgPUmo) as well as an [appimage](https://drive.protonmail.com/urls/3B025NJVQ4#rKUaWu6IJb5o). They're both built on Bullseye, so I guess I'll have to build more on Buster, but these ones work, at least on Bullseye...

**Comment by Jai-JAP** [comment]
Can u build arm64 hyper as well...? as official arm64 builds are broken

**Comment by Crilum** [comment]
Yeah, it will be later though...

**Comment by Crilum** [comment]
I'm building some on buster right now..

**Comment by Jai-JAP** [comment]
> Yeah, it will be later though...

Build em on arm64 buster as well

Also can u build the previous versions of hyper prior to 3.2.0

**Comment by Crilum** [comment]
I don't think I can build all of the versions of hyper (seems more like a job for a GH Action), but I can build the latest..

**Comment by Jai-JAP** [comment]
Have you successfully built armhf and arm64 versions?

**Comment by Crilum** [comment]
I haven't continued building on buster, and I haven't yet build anything on arm64.. 
I can probably get it done today..

**Comment by Jai-JAP** [comment]
@Crilum i have got the GitHub actions workflow successfully running and now it will get new releases and build them automatically. Also the older versions 3.2.1 and 3.2.2 are built along with the latest version 3.2.3.

You can find the builds [here](https://github.com/Jai-JAP/hyper-arm-builds/releases)
