### ISSUE TITLE
why the different use of buster and bionic docker containers in builds?

### ISSUE THREAD

**Issue by theofficialgman** [Jai-JAP/hyper-arm-builds#3]
why have you swapped between using buster and bionic docker containers? currently armhf builds using a bionic armhf docker container, and arm64 builds using an arm64 docker container. this was switched the other way at one point.

what is the reason for changing?

**Comment by Jai-JAP** [comment]
it has just gotten ignored unintentionally

**Comment by Jai-JAP** [comment]
ubuntu bionic arm64 errors out at  `Error: ERROR: Playwright does not support firefox on ubuntu18.04-arm64`

see actions run https://github.com/Jai-JAP/hyper-arm-builds/actions/runs/2483950371

**Comment by theofficialgman** [comment]
annoying.. playwright is only use for testing electron in hyper. firefox of course is not used (this is an electron app)
you can see its only use is here: https://github.com/vercel/hyper/blob/bc37efdc23991effe3e6111a8c4ca6f00319063b/test/index.ts#L7

this was a known issue and has been fixed upstream at playwright https://github.com/microsoft/playwright/issues/823

you can now disable unwanted downloads following this https://github.com/microsoft/playwright/issues/823
unfortunatly, this is an upstream hyper issue, they need to depend on playwright-core instead and implement a install.js file

**Comment by theofficialgman** [comment]
@Jai-JAP playwright works
just disable downloading the files like so. since this is testing electron, no downloads are needed
```
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 yarn --network-timeout 1000000 &&
```

I've been testing on my own github actions. this works but I'm getting a totally unrelated issue now with all builds 
you can see here: https://github.com/theofficialgman/hyper-arm-builds/runs/6855270513?check_suite_focus=true
it builds fine, then runs into conflicting depends on both armhf and arm64...

**Comment by Jai-JAP** [comment]
Can you test disabling just firefox 
Maybe PLAYWRIGHT_SKIP_FIREFOX_DOWNLOAD=1 or so will work
if that works I'll revert to ubuntu-core:arm64-bionic

**Comment by Jai-JAP** [comment]
also the new errors are upstream ones
Probably because the dependency tree has been altered by an update to xterm-addon-fit

**Comment by theofficialgman** [comment]
I got it to build. PR incoming https://github.com/theofficialgman/hyper-arm-builds/releases/tag/v3.2.3

**Comment by Jai-JAP** [comment]
did u try just disabling firefox and not all browsers

**Comment by Jai-JAP** [comment]
also are the builds tested as i cant test due to my pi being extremely laggy and unusable

**Comment by theofficialgman** [comment]
> did u try just disabling firefox and not all browsers

@Jai-JAP this is not an option. disabling a single browser requires an entire new file to be created in upstream hyper repository
no browsers needed to be download at all. refer to the documentation. the "skip" variable you listed does not exist

https://playwright.bootcss.com/python/docs/installation#skip-browser-downloads
